aplikacje_webowe/django_applications/examples/blog/urls.py
from django.urls import path
from blog.views import posts_list, post_details

app_name = 'blog'
urlpatterns = [
    path('', posts_list, name='list'),
    path("<int:id>/", post_details, name="details"),
]

aplikacje_webowe/django_applications/examples/books/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import books_list, book_details, form_view, HomeTemplateView, BookListView, BookCreateView, BookDetailView

app_name = "books" # przestrzeń nazw aplikacji
urlpatterns = [
    path("", HomeTemplateView.as_view(), name="home"),
    path("books/", BookListView.as_view(), name="list"),
    path("books/create", BookCreateView.as_view(), name="create"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="details"),
    path("formview/", form_view, name="formview")

]

aplikacje_webowe/django_applications/examples/examples/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls")),
    path("", include("plots.urls")),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplikacje_webowe/django_applications/examples/books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=256)
    author = models.CharField(max_length=256)
    description = models.TextField()
    published_at = models.DateField(auto_now_add=True)
    cover_image = models.ImageField(upload_to='books/%Y/%m/%d/', blank=True, null=True)
    category = models.CharField(max_length=256, blank=True, null=True)
    def __str__(self):
        return f"{self.title} ({self.author})"

aplikacje_webowe/django_applications/examples/books/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset
from django import forms
from django.forms import formset_factory

from .models import Book

CATEGORY_CHOICES = (
    ('fantasy', 'Fantastyka'),
    ('horror', 'Horror'),
    ('sci-fi', 'Science Fiction'),
    ('romance', 'Romans'),
    ('thriller', 'Thriller'),
)

class BookForm(forms.Form):
    title = forms.CharField(label='Tytuł', max_length=256)
    author = forms.CharField(label='Autor', max_length=256)
    description = forms.CharField(label='Opis', max_length=1000, widget=forms.Textarea)
    cover_image = forms.ImageField(label='Okładka', required=False)
    category = forms.ChoiceField(label='Kategoria', required=False, choices=CATEGORY_CHOICES)

    def clean_title(self):
        title = self.cleaned_data['title']
        return title.capitalize()

    def clean_author(self):
        author = self.cleaned_data['author']
        return author.title()

class BookForm2(forms.ModelForm):
    category = forms.ChoiceField(label='Kategoria', required=False, choices=CATEGORY_CHOICES)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset("Dodawanie Posta", "title", "author", "description", "cover_image", "category"),
            Submit("submit", "Zapisz"),
        )
    class Meta:
        model = Book
        fields = "__all__"


    def clean_title(self):
        title = self.cleaned_data['title']
        return title.capitalize()

    def clean_author(self):
        author = self.cleaned_data['author']
        return author.title()


class MyForm(forms.Form):
    name = forms.CharField(label='Name')
    email = forms.EmailField(label='Email')

MyFormSet = formset_factory(MyForm, extra=2)

aplikacje_webowe/django_applications/examples/books/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, CreateView, DetailView
from books.models import Book
from django.urls import reverse_lazy

# Create your views here.
from .forms import BookForm, BookForm2, MyForm, MyFormSet

class HomeTemplateView(TemplateView):
    template_name = "books/base.html"
def books_list(request):
    books = Book.objects.all()

    if request.method == "POST":
        form = BookForm2(request.POST, request.FILES)
        if form.is_valid():
            form.save()

    form = BookForm2()

    return render(request, "books/list.html", {"books": books, "form": form})

class BookListView(ListView):
    template_name = "books/list.html"
    model = Book
    context_object_name = "books"


class BookCreateView(CreateView):
    template_name = "books/list.html"
    model = Book
    form_class = BookForm2
    success_url = reverse_lazy("books:list")


class BookDetailView(DetailView):
    template_name = "books/details.html"
    model = Book
    context_object_name = "book"

def book_details(request, pk):
    book = Book.objects.get(pk=pk)
    return render(request, "books/details.html", {"book": book})


def form_view(request):
    formset = MyFormSet(request.POST or None)

    if request.method == 'POST':
        if formset.is_valid():
            for form in formset:
                print(form.cleaned_data)

    return render(request, 'my_template.html', {'formset': formset})

aplikacje_webowe/django_applications/examples/books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
 </head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:list' %}">Books</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:list' %}">Posts</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout ({{user}})</a>
          {% else %}
          <a class="nav-link" href="{% url 'login' %}">Login</a>
          {% endif %}
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="container">
{% block content %}
{% endblock %}
</div>


 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

aplikacje_webowe/django_applications/examples/books/templates/books/details.html
{% extends "books/base.html" %}
{% load thumbnail %}

{% block content %}
  <h2>{{ book.title }}</h2>
  <p>{{ book.author }}</p>
  <p>{{ book.description }}</p>
  <p><img src="{{ book.cover_image.url }}" width="400px"></p>

<p>
  
  {% thumbnail book.cover_image "400" as im %}
    <img src="{{ im.url }}">
  {% endthumbnail %}
  
</p>
{% endblock %}

aplikacje_webowe/django_applications/examples/books/templates/books/list.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}Lista książek{% endblock %}

{% block content %}
{% for book in books %}
<p>
  <h2><a href='{% url "books:details" book.id %}'>{{ book.title }}</a></h2>
  {% thumbnail book.cover_image "50" as im %}
    <img src="{{ im.url }}">
  {% endthumbnail %}

</p>
{% endfor %}

<div>
  {% if form %}
  {% crispy form %}
  {% endif %}
</div>


{% endblock %}